apiVersion: batch/v1
kind: Job
metadata:
  generateName: awave-sweep-a100-
spec:
  completions: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      name: awave-pod
    spec:
      activeDeadlineSeconds: 3600
      containers:
      - name: run
        image: $container
        env:
          - name: OMP_TARGET_OFFLOAD
            value: MANDATORY
        command:
          - bash
          - -lc
          - >-
            set -euo pipefail;
            run_case() {
              echo "===== CASE shape=$1 nsteps=$2 out_period=$3 =====";
              stdbuf -oL -eL build-dev/awave -shape "$1" -nsteps "$2" -out_period "$3" "/tmp/awave-sweep-$4";
              rm -f "/tmp/awave-sweep-$4"*.vtkhdf || true;
            };
            run_case 32,32,32 200 100 32;
            run_case 64,64,64 200 100 64;
            run_case 96,96,96 200 100 96;
            run_case 128,128,128 20 10 128;
            run_case 192,192,192 20 10 192;
            run_case 256,256,256 20 10 256;
            run_case 384,384,384 20 10 384;
        resources:
          requests:
            cpu: 1
            memory: 16Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 1
            memory: 16Gi
            nvidia.com/gpu: 1
      restartPolicy: Never
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
